# This file was @generated by cargo2nix 0.12.0.
# It is not intended to be manually edited.

args@{
  release ? true,
  rustPackages,
  hostPlatformCpu ? null,
  hostPlatformFeatures ? [ ],
  target ? null,
  codegenOpts ? null,
  profileOpts ? null,
  cargoUnstableFlags ? null,
  rustcLinkFlags ? null,
  rustcBuildFlags ? null,
  mkRustCrate,
  rustLib,
  lib,
  ignoreLockHash,
  cargoConfig ? { },
}:
let
  nixifiedLockHash = "bdcf5f5b7168a26e3dc0e417d153fef29f1ab7654360523d4860480716b67ec6";
  workspaceSrc = if args.workspaceSrc == null then ./. else args.workspaceSrc;
  currentLockHash = builtins.hashFile "sha256" (workspaceSrc + /Cargo.lock);
  lockHashIgnored =
    if ignoreLockHash then builtins.trace "Ignoring lock hash" ignoreLockHash else ignoreLockHash;
in
if !lockHashIgnored && (nixifiedLockHash != currentLockHash) then
  throw "Cargo.nix ${nixifiedLockHash} is out of sync with Cargo.lock ${currentLockHash}"
else
  let
    inherit (rustLib)
      fetchCratesIo
      fetchCrateLocal
      decideProfile
      genDrvsByProfile
      ;
    cargoConfig' =
      if cargoConfig != { } then
        cargoConfig
      else if builtins.pathExists ./.cargo/config then
        lib.importTOML ./.cargo/config
      else if builtins.pathExists ./.cargo/config.toml then
        lib.importTOML ./.cargo/config.toml
      else
        { };
    profilesByName = {
    };
    overridableMkRustCrate =
      f:
      let
        drvs = genDrvsByProfile profilesByName (
          { profile, profileName }:
          mkRustCrate (
            {
              inherit
                release
                profile
                hostPlatformCpu
                hostPlatformFeatures
                target
                profileOpts
                codegenOpts
                cargoUnstableFlags
                rustcLinkFlags
                rustcBuildFlags
                ;
              cargoConfig = cargoConfig';
            }
            // (f profileName)
          )
        );
      in
      {
        compileMode ? null,
        profileName ? decideProfile compileMode release,
      }:
      let
        drv = drvs.${profileName};
      in
      if compileMode == null then drv else drv.override { inherit compileMode; };
  in
  {
    cargo2nixVersion = "0.12.0";
    workspace = {
      aoc_2025 = rustPackages.unknown.aoc_2025."0.1.0";
    };
    "registry+https://github.com/rust-lang/crates.io-index".aho-corasick."1.1.4" =
      overridableMkRustCrate
        (profileName: rec {
          name = "aho-corasick";
          version = "1.1.4";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
          src = fetchCratesIo {
            inherit name version;
            sha256 = "ddd31a130427c27518df266943a5308ed92d4b226cc639f5a8f1002816174301";
          };
          features = builtins.concatLists [
            [ "perf-literal" ]
            [ "std" ]
          ];
          dependencies = {
            memchr =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" {
                inherit profileName;
              }).out;
          };
        });

    "unknown".aoc_2025."0.1.0" = overridableMkRustCrate (profileName: rec {
      name = "aoc_2025";
      version = "0.1.0";
      registry = "unknown";
      src = fetchCrateLocal workspaceSrc;
      dependencies = {
        regex =
          (rustPackages."registry+https://github.com/rust-lang/crates.io-index".regex."1.12.2" {
            inherit profileName;
          }).out;
      };
    });

    "registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" =
      overridableMkRustCrate
        (_profileName: rec {
          name = "memchr";
          version = "2.7.6";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
          src = fetchCratesIo {
            inherit name version;
            sha256 = "f52b00d39961fc5b2736ea853c9cc86238e165017a493d1d5c8eac6bdc4cc273";
          };
          features = builtins.concatLists [
            [ "alloc" ]
            [ "std" ]
          ];
        });

    "registry+https://github.com/rust-lang/crates.io-index".regex."1.12.2" =
      overridableMkRustCrate
        (profileName: rec {
          name = "regex";
          version = "1.12.2";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
          src = fetchCratesIo {
            inherit name version;
            sha256 = "843bc0191f75f3e22651ae5f1e72939ab2f72a4bc30fa80a066bd66edefc24d4";
          };
          features = builtins.concatLists [
            [ "default" ]
            [ "perf" ]
            [ "perf-backtrack" ]
            [ "perf-cache" ]
            [ "perf-dfa" ]
            [ "perf-inline" ]
            [ "perf-literal" ]
            [ "perf-onepass" ]
            [ "std" ]
            [ "unicode" ]
            [ "unicode-age" ]
            [ "unicode-bool" ]
            [ "unicode-case" ]
            [ "unicode-gencat" ]
            [ "unicode-perl" ]
            [ "unicode-script" ]
            [ "unicode-segment" ]
          ];
          dependencies = {
            aho_corasick =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".aho-corasick."1.1.4" {
                inherit profileName;
              }).out;
            memchr =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" {
                inherit profileName;
              }).out;
            regex_automata =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".regex-automata."0.4.13" {
                inherit profileName;
              }).out;
            regex_syntax =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".regex-syntax."0.8.8" {
                inherit profileName;
              }).out;
          };
        });

    "registry+https://github.com/rust-lang/crates.io-index".regex-automata."0.4.13" =
      overridableMkRustCrate
        (profileName: rec {
          name = "regex-automata";
          version = "0.4.13";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
          src = fetchCratesIo {
            inherit name version;
            sha256 = "5276caf25ac86c8d810222b3dbb938e512c55c6831a10f3e6ed1c93b84041f1c";
          };
          features = builtins.concatLists [
            [ "alloc" ]
            [ "dfa-onepass" ]
            [ "hybrid" ]
            [ "meta" ]
            [ "nfa-backtrack" ]
            [ "nfa-pikevm" ]
            [ "nfa-thompson" ]
            [ "perf-inline" ]
            [ "perf-literal" ]
            [ "perf-literal-multisubstring" ]
            [ "perf-literal-substring" ]
            [ "std" ]
            [ "syntax" ]
            [ "unicode" ]
            [ "unicode-age" ]
            [ "unicode-bool" ]
            [ "unicode-case" ]
            [ "unicode-gencat" ]
            [ "unicode-perl" ]
            [ "unicode-script" ]
            [ "unicode-segment" ]
            [ "unicode-word-boundary" ]
          ];
          dependencies = {
            aho_corasick =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".aho-corasick."1.1.4" {
                inherit profileName;
              }).out;
            memchr =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".memchr."2.7.6" {
                inherit profileName;
              }).out;
            regex_syntax =
              (rustPackages."registry+https://github.com/rust-lang/crates.io-index".regex-syntax."0.8.8" {
                inherit profileName;
              }).out;
          };
        });

    "registry+https://github.com/rust-lang/crates.io-index".regex-syntax."0.8.8" =
      overridableMkRustCrate
        (_profileName: rec {
          name = "regex-syntax";
          version = "0.8.8";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
          src = fetchCratesIo {
            inherit name version;
            sha256 = "7a2d987857b319362043e95f5353c0535c1f58eec5336fdfcf626430af7def58";
          };
          features = builtins.concatLists [
            [ "default" ]
            [ "std" ]
            [ "unicode" ]
            [ "unicode-age" ]
            [ "unicode-bool" ]
            [ "unicode-case" ]
            [ "unicode-gencat" ]
            [ "unicode-perl" ]
            [ "unicode-script" ]
            [ "unicode-segment" ]
          ];
        });

  }
